
CL-USER 1 > (quadrado 2)

Error: Undefined operator QUADRADO in form (QUADRADO 2).
  1 (continue) Try invoking QUADRADO again.
  2 Return some values from the form (QUADRADO 2).
  3 Try invoking something other than QUADRADO with the same arguments.
  4 Set the symbol-function of QUADRADO to another function.
  5 Set the macro-function of QUADRADO to another function.
  6 (abort) Return to top loop level 0.

Type :b for backtrace or :c <option number> to proceed.
Type :bug-form "<subject>" for a bug report template or :? for other options.

CL-USER 2 : 1 > (quadrado 2)
4

CL-USER 3 : 1 > 